from solution import init, add, move, search, go

init()
a = add("beyond", 10)
print(a.no, a.word)
a = add("person", 8)
print(a.no, a.word)
a = move(-1)
print(a.no, a.word)
a = add("earth", 5)
print(a.no, a.word)
a = search("fun")
print(a.no, a.word)
a = move(1)
print(a.no, a.word)
a = move(-1)
print(a.no, a.word)
a = move(-1)
print(a.no, a.word)
a = add("best", 7)
print(a.no, a.word)
a = move(-1)
print(a.no, a.word)
a = move(1)
print(a.no, a.word)
a = add("plant", 7)
print(a.no, a.word)
a = add("plan", 2)
print(a.no, a.word)
a = move(-1)
print(a.no, a.word)
a = add("place", 3)
print(a.no, a.word)
a = add("please", 8)
print(a.no, a.word)
a = search("plan")
print(a.no, a.word)
a = move(1)
print(a.no, a.word)
a = search("pla")
print(a.no, a.word)
a = search("pl")
print(a.no, a.word)
a = search("p")
print(a.no, a.word)
a = add("permit", 8)
print(a.no, a.word)
a = search("p")
print(a.no, a.word)
a = go(10)
print(a.no, a.word)
a = move(-1)
print(a.no, a.word)
a = go(4)
print(a.no, a.word)
a = move(1)
print(a.no, a.word)
a = move(1)
print(a.no, a.word)
a = go(3)
print(a.no, a.word)